multi_stat/main/urls.py
from django.urls import path
from .views import index, contacts, about

app_name = "main"

urlpatterns = [
    path("contacts/", contacts, name="contacts"),
    path("about-us/", about, name="about"),
    path("", index, name="index"),
]

multi_stat/multi_stat/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("analytic/", include("statistics_and_analytics.urls")),
    path("socials/", include("socials.urls")),
    path("", include("main.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

multi_stat/socials/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from .views import register, ProfileUpdateView, ProfileView
from django.conf import settings
from django.conf.urls.static import static

app_name = "socials"

urlpatterns = (
    [
        path(
            "login/",
            LoginView.as_view(template_name="socials/login.html"),
            name="login",
        ),
        path("logout/", LogoutView.as_view(next_page="main:index"), name="logout"),
        path("register/", register, name="register"),
        path(
            "profile/<int:pk>/update/",
            ProfileUpdateView.as_view(),
            name="profile_update",
        ),
        path("profile/<int:pk>/", ProfileView.as_view(), name="profile_view"),
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

multi_stat/socials/models.py
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name="профиль")
    username = models.CharField(max_length=100, default="-------")
    password = models.CharField(max_length=20, default="1111")
    phone = models.CharField(
        max_length=20, blank=True, null=True, verbose_name="телефон"
    )
    email = models.EmailField(unique=True, verbose_name="электронная почта")
    avatar = models.ImageField(
        upload_to="profiles/profile",
        null=True,
        default="profiles/profile/ava-default.png",
    )

    def __str__(self):
        return self.username

    class Meta:
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"

multi_stat/socials/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class RegisterForm(forms.ModelForm):
    password = forms.CharField()

    class Meta:
        model = Profile
        fields = ("username", "phone", "email")


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ("username", "phone", "email", "avatar")

multi_stat/socials/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.contrib.auth import authenticate, login
from .forms import LoginForm, RegisterForm, ProfileForm
from .models import Profile
from django.db import IntegrityError
from django.views.generic.edit import UpdateView
from django.views.generic.detail import DetailView


def register(request):
    if request.method == "POST":
        user_form = RegisterForm(request.POST)
        if user_form.is_valid():
            try:
                username = user_form.cleaned_data["username"]
                password = user_form.cleaned_data["password"]
                user = User.objects.create_user(username=username)
                user.set_password(password)
                user.save()
                login(request, user)
                profile = Profile.objects.create(
                    user=user,
                    username=username,
                    password=password,
                    phone=user_form.cleaned_data["phone"],
                    email=user_form.cleaned_data["email"],
                )
                profile.save()
                return redirect("/")
            except IntegrityError:
                form.add_error("login", "Пользователь с таким логином уже существует")
    else:
        user_form = RegisterForm()
    return render(request, "socials/register.html", {"user_form": user_form})


class ProfileUpdateView(UpdateView):
    model = Profile
    form_class = ProfileForm
    success_url = "/"


class ProfileView(DetailView):
    template_name = "socials/profile.html"
    model = Profile
    context_object_name = "profile"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        profile = self.object
        context["profile"] = profile
        return context

multi_stat/socials/templates/socials/login.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}Вход{% endblock %}

{% block content %}

<section class="u-clearfix u-palette-1-light-3 u-section-1" id="carousel_9c5c">
    <div class="u-clearfix u-sheet u-sheet-1">
        <h2 class="u-align-center u-text u-text-default u-text-1"> Выполните вход</h2>
        <div class="u-align-left-lg u-align-left-xl u-palette-2-base u-preserve-proportions u-shape u-shape-circle u-shape-1"></div>
        <div class="u-expanded-width-sm u-expanded-width-xs u-form u-form-1">
            <form method="post" action="{% url 'socials:login' %}">
                {% csrf_token %}
                <div class="u-form-group u-form-name">
                    <label for="name-e893" class="u-label">Имя</label>
                    <input type="text" placeholder="Enter your Name" id="name-e893" name="username"
                           class="u-border-none u-input u-input-rectangle u-radius u-input-1" required="">
                </div>
                <div class="u-form-email u-form-group">
                    <label for="password-e893" class="u-label">Пароль</label>
                    <input type="password" placeholder="Enter your password" id="password-e893" name="password"
                           class="u-border-none u-input u-input-rectangle u-radius u-input-2" required="">
                </div>
                <input type="submit" value="Вход" style="margin-top:10px; background-color: DarkOrchid; color: white; font-size: bold; border-radius: 5px; width: 150px;">
                <input type="hidden" name="next" value="{{ next }}">
            </form>
        </div>
        <div class="u-palette-1-base u-preserve-proportions u-shape u-shape-circle u-shape-2"></div>
    </div>
</section>


{% endblock %}

multi_stat/socials/templates/socials/profile.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}
Профиль пользователя {{profile.username}}
{% endblock %}
{% block content %}
<div style="margin: 100px">
    <div>
        <div class="col-md-6">
            <div class="text-center">
                <h1>{{ profile.username }}</h1>
                <img src="{{ profile.avatar.url }}" width="250px" style="border-radius: 5px">
            </div>
            <table style="border-collapse: collapse; width: 50%; margin: 15px">
                <tr>
                    <th style="border: 1px solid #dddddd; text-align: left; padding: 8px; background-color: #f2f2f2;"
                        colspan="2">Информация о пользователе
                    </th>
                </tr>
                <tr>
                    <td style="border: 1px solid #dddddd; text-align: left; padding: 8px;">
                        {{ profile.username }}
                    </td>
                </tr>
                <tr>
                    <td style="border: 1px solid #dddddd; text-align: left; padding: 8px;">
                        <a href="mailto:{{profile.email}}:">{{ profile.email }}</a>
                    </td>
                </tr>
                <tr>
                    <td style="border: 1px solid #dddddd; text-align: left; padding: 8px;">
                        <a href="tel:{{ profile.phone }}">{{ profile.phone }}</a>
                    </td>
                </tr>
            </table>
            <div>
                <a style="margin-top:10px; padding: 10px; background-color: DarkOrchid; color: white; font-size: bold; border-radius: 5px; width: 250px"
                   href="{% url 'socials:profile_update' pk=profile.id %}">Изменить!</a>
            </div>
        </div>
    </div>
</div>


{% endblock %}

multi_stat/socials/templates/socials/profile_form.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}
Изменение профиля
{% endblock %}

{% block content %}

<section class="u-clearfix u-palette-1-light-3 u-section-1" id="carousel_9c5c">
    <div class="u-clearfix u-sheet u-sheet-1">
        <h2 class="u-align-center u-text u-text-default u-text-1"> Изменение профиля</h2>
        <div class="u-align-left-lg u-align-left-xl u-palette-2-base u-preserve-proportions u-shape u-shape-circle u-shape-1"></div>
        <div class="u-expanded-width-sm u-expanded-width-xs u-form u-form-1">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="u-form-group u-form-name">
                    <p>
                        <label for="id_username" class="u-label">Имя</label>
                        <input type="text" name="username" value="{{ user.profile.username }}" maxlength="100" required="" id="id_username"
                               class="u-border-none u-input u-input-rectangle u-radius u-input-1">
                    </p>
                </div>
                <div class="u-form-group u-form-name">
                    <p>
                        <label for="id_phone" class="u-label">Телефон</label>
                        <input type="text" name="phone" value="{{ user.profile.phone }}" maxlength="20" id="id_phone"
                               class="u-border-none u-input u-input-rectangle u-radius u-input-1">
                    </p>
                </div>
                <div class="u-form-group u-form-name">
                    <p>
                        <label for="id_email" class="u-label">Электронная почта:</label>
                        <input type="email" name="email" value="{{ user.profile.email }}" maxlength="254" required=""
                               id="id_email" class="u-border-none u-input u-input-rectangle u-radius u-input-1">
                    </p>
                </div>
                <div class="u-form-group u-form-name">
                    <p>
                        <br>
                        <img src="{{ user.profile.avatar.url }}" width="150px"><br>
                        <input type="file" name="avatar" accept="image/*" id="id_avatar" style="margin-top:10px; background-color: DarkOrchid; color: white; font-size: bold; border-radius: 5px; width: 350px;">
                    </p>
                </div>
                <input type="submit" value="Изменить профиль"
                       style="margin-top:10px; background-color: DarkOrchid; color: white; font-size: bold; border-radius: 5px; width: 200px;">
            </form>
        </div>
        <div class="u-palette-1-base u-preserve-proportions u-shape u-shape-circle u-shape-2"></div>
    </div>
</section>
{% endblock %}

multi_stat/socials/templates/socials/register.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}Регистрация{% endblock %}

{% block content %}

<section class="u-clearfix u-palette-1-light-3 u-section-1" id="carousel_9c5c">
    <div class="u-clearfix u-sheet u-sheet-1">
        <h2 class="u-align-center u-text u-text-default u-text-1"> Регистрация пользователя</h2>
        <div class="u-align-left-lg u-align-left-xl u-palette-2-base u-preserve-proportions u-shape u-shape-circle u-shape-1"></div>
        <div class="u-expanded-width-sm u-expanded-width-xs u-form u-form-1">
            <form method="post" action="{% url 'socials:register' %}">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="u-form-group u-form-name">
                    <label for="name-e893" class="u-label">Имя</label>
                    <input type="text" placeholder="Enter your Name" id="name-e893" name="username"
                           class="u-border-none u-input u-input-rectangle u-radius u-input-1" required="">
                </div>
                <div class="u-form-group u-form-name">
                    <label for="name-fe893" class="u-label">Фамилия</label>
                    <input type="text" placeholder="Enter your Name" id="name-fe893" name="first_name"
                           class="u-border-none u-input u-input-rectangle u-radius u-input-1" required="">
                </div>
                <div class="u-form-group u-form-name">
                    <label for="em" class="u-label">Электронная почта</label>
                    <input type="email" placeholder="Enter your Name" id="em" name="email"
                           class="u-border-none u-input u-input-rectangle u-radius u-input-1" required="">
                </div>
                <div class="u-form-group u-form-name">
                    <label for="ph" class="u-label">Телефон</label>
                    <input type="tel" placeholder="Enter your Name" id="ph" name="phone"
                           class="u-border-none u-input u-input-rectangle u-radius u-input-1">
                </div>
                <div class="u-form-email u-form-group">
                    <label for="password-e893" class="u-label">Пароль</label>
                    <input type="password" placeholder="Enter your password" id="password-e893" name="password"
                           class="u-border-none u-input u-input-rectangle u-radius u-input-2" required="">
                </div>
                <div class="u-form-email u-form-group">
                    <label for="password-2e893" class="u-label">Повторите пароль</label>
                    <input type="password" placeholder="Enter your password" id="password-2e893" name="password2"
                           class="u-border-none u-input u-input-rectangle u-radius u-input-2" required="">
                </div>
                <input type="submit" value="Создать аккаунт" style="margin-top:10px; background-color: DarkOrchid; color: white; font-size: bold; border-radius: 5px; width: 150px;">

            </form>
        </div>
        <div class="u-palette-1-base u-preserve-proportions u-shape u-shape-circle u-shape-2"></div>
    </div>
</section>


{% endblock %}

multi_stat/socials/templates/socials/register_done.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}Регистрация завершена{% endblock %}

{% block content %}

<section class="u-clearfix u-palette-1-light-3 u-section-1" id="carousel_9c5c">

    <h1>Welcome {{ new_user.first_name }}!</h1>
    <p>
        Your account has been successfully created. Now you can <a href="{% url 'socials:login' %}">log in</a>.
    </p>

</section>


{% endblock %}