multi_stat/main/urls.py
from django.urls import path
from .views import index, contacts, about

app_name = "main"

urlpatterns = [
    path("contacts/", contacts, name="contacts"),
    path("about-us/", about, name="about"),
    path("", index, name="index"),
]

multi_stat/multi_stat/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("analytic/", include("statistics_and_analytics.urls")),
    path("socials/", include("socials.urls")),
    path("", include("main.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

multi_stat/statistics_and_analytics/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import (
    analytics,
    seo_detail_view,
    ads_detail,
    other_detail,
    dataloading_dates,
    analytics_for_date,
)

app_name = "saa"

urlpatterns = (
    [
        path("seo-report/<int:page>/", seo_detail_view, name="seo_report"),
        path("other-ads-report/<int:page>/", other_detail, name="other_ads_report"),
        path("ads-report/<int:page>/", ads_detail, name="ads_report"),
        path("dashboard/<int:page>/", analytics, name="analytics"),
        path("dataloading-dates/", dataloading_dates, name="dates"),
        path("analytic-for-date/<str:date>/", analytics_for_date, name="a_for_dates"),
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

multi_stat/statistics_and_analytics/models.py
from django.db import models


class SEOReport(models.Model):
    title = models.CharField(max_length=100, default="SEO", verbose_name="Название")
    visits = models.PositiveIntegerField(default=0, verbose_name="Визиты")
    all_expense = models.PositiveIntegerField(default=0, verbose_name="Расход")
    transactions = models.PositiveIntegerField(default=0, verbose_name="Заявки")
    avg_check = models.PositiveIntegerField(default=0, verbose_name="Средний чек")
    income = models.PositiveIntegerField(default=0, verbose_name="Доход")
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "SEO отчет"
        verbose_name_plural = "SEO отчеты"
        ordering = ["-created"]
        indexes = [
            models.Index(fields=["-created"]),
        ]


class SEOReportDetail(models.Model):
    title = models.CharField(max_length=100, default="-----", verbose_name="Название")
    visits = models.PositiveIntegerField(default=0, verbose_name="Визиты")
    impressions = models.PositiveIntegerField(
        default=0, blank=True, null=True, verbose_name="Показы"
    )
    ctr = models.DecimalField(
        default=0,
        verbose_name="CTR",
        blank=True,
        null=True,
        decimal_places=2,
        max_digits=10,
    )
    avg_position = models.DecimalField(
        default=0,
        blank=True,
        null=True,
        verbose_name="Средняя позиция",
        decimal_places=2,
        max_digits=10,
    )
    convert = models.DecimalField(
        default=0,
        blank=True,
        null=True,
        verbose_name="Конверсия",
        decimal_places=3,
        max_digits=15,
    )
    transactions = models.PositiveIntegerField(default=0, verbose_name="Заявки")
    created = models.DateTimeField(auto_now_add=True)
    category = models.ForeignKey(
        "SEOReport",
        on_delete=models.CASCADE,
        related_name="report",
        verbose_name="Канал трафика",
    )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "SEO отчет детально"
        verbose_name_plural = "SEO отчеты детально"
        ordering = ["-created"]
        indexes = [
            models.Index(fields=["-created"]),
        ]


class YandexSEOReport(SEOReportDetail):
    class Meta:
        verbose_name = "SEO Яндекс отчет"
        verbose_name_plural = "SEO Яндекс отчеты"
        ordering = ["-created"]


class GoogleSEOReport(SEOReportDetail):
    class Meta:
        verbose_name = "SEO Google отчет"
        verbose_name_plural = "SEO Google отчеты"
        ordering = ["-created"]


class DirectSEOReport(SEOReportDetail):
    class Meta:
        verbose_name = "SEO Прямые заходы отчет"
        verbose_name_plural = "SEO Прямые заходы отчеты"
        ordering = ["-created"]


class ReferralsSEOReport(SEOReportDetail):
    class Meta:
        verbose_name = "SEO Ссылочные заходы отчет"
        verbose_name_plural = "SEO Ссылочные заходы отчеты"
        ordering = ["-created"]


class Ads(models.Model):
    title = models.CharField(max_length=100, default="-----", verbose_name="Название")
    average_check = models.PositiveIntegerField(default=0, verbose_name="Средний чек")
    views = models.PositiveIntegerField(default=0, verbose_name="Показы")
    visits = models.PositiveIntegerField(default=0, verbose_name="Визиты")
    ctr = models.DecimalField(
        default=0,
        verbose_name="CTR",
        blank=True,
        null=True,
        decimal_places=2,
        max_digits=10,
    )
    cta = models.PositiveIntegerField(default=0, verbose_name="Стоимость клика")
    transactions = models.PositiveIntegerField(default=0, verbose_name="Заявки")
    all_expense = models.PositiveIntegerField(default=0, verbose_name="Расход")
    income = models.PositiveIntegerField(default=0, verbose_name="Доход")
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ["-created"]
        indexes = [
            models.Index(fields=["-created"]),
        ]


class YandexDirect(Ads):
    class Meta:
        verbose_name = "Yandex Direct отчет"
        verbose_name_plural = "Yandex Direct отчеты"


class GoogleAds(Ads):
    class Meta:
        verbose_name = "Google Ads отчет"
        verbose_name_plural = "Google Ads отчеты"


class VKAds(Ads):
    class Meta:
        verbose_name = "VK Ads отчет"
        verbose_name_plural = "VK Ads отчеты"


class FacebookAds(Ads):
    class Meta:
        verbose_name = "Facebook Ads отчет"
        verbose_name_plural = "Facebook Ads отчеты"


class InstagramAds(Ads):
    class Meta:
        verbose_name = "Instagram Ads отчет"
        verbose_name_plural = "Instagram Ads отчеты"


class MyTarget(Ads):
    class Meta:
        verbose_name = "MyTarget Ads отчет"
        verbose_name_plural = "MyTarget Ads отчеты"


class OtherAds(models.Model):
    title = models.CharField(max_length=100, default="-----", verbose_name="Название")
    visits = models.PositiveIntegerField(default=0, verbose_name="Визиты")
    transactions = models.PositiveIntegerField(default=0, verbose_name="Заявки")
    all_expense = models.PositiveIntegerField(default=0, verbose_name="Расход")
    convert = models.DecimalField(
        default=0,
        blank=True,
        null=True,
        verbose_name="Конверсия",
        decimal_places=3,
        max_digits=15,
    )
    income = models.PositiveIntegerField(default=0, verbose_name="Доход")
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ["-created"]
        indexes = [
            models.Index(fields=["-created"]),
        ]


class TelegramAds(OtherAds):
    class Meta:
        verbose_name = "Telegram Ads отчет"
        verbose_name_plural = "Telegram Ads отчеты"


class EmailTracking(OtherAds):
    class Meta:
        verbose_name = "EmailTracking отчет"
        verbose_name_plural = "EmailTracking отчеты"


class CallTracking(OtherAds):
    class Meta:
        verbose_name = "CallTracking отчет"
        verbose_name_plural = "CallTracking отчеты"

multi_stat/statistics_and_analytics/views.py
from datetime import datetime
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import cache_page
from .graph_maker import make_graph
from .models import (
    SEOReport,
    YandexSEOReport,
    GoogleSEOReport,
    DirectSEOReport,
    ReferralsSEOReport,
    YandexDirect,
    GoogleAds,
    VKAds,
    FacebookAds,
    InstagramAds,
    MyTarget,
    TelegramAds,
    EmailTracking,
    CallTracking,
)


@login_required()
# @cache_page(60 * 60)
def analytics(request, page):
    seo = SEOReport.objects.all()[:10]
    ya_d = YandexDirect.objects.all()[:10]
    go_a = GoogleAds.objects.all()[:10]
    vk_a = VKAds.objects.all()[:10]
    fb_a = FacebookAds.objects.all()[:10]
    in_a = InstagramAds.objects.all()[:10]
    my_t = MyTarget.objects.all()[:10]
    tg_a = TelegramAds.objects.all()[:10]
    em_t = EmailTracking.objects.all()[:10]
    ca_t = CallTracking.objects.all()[:10]
    ind = [i for i in range(1, len(seo) + 1)]
    dates = list(map(lambda d: d.strftime("%Y-%m-%d"), [s.created for s in seo]))
    data = list(
        zip(
            seo,
            ya_d,
            go_a,
            vk_a,
            fb_a,
            in_a,
            my_t,
            tg_a,
            em_t,
            ca_t,
        )
    )

    graph = make_graph(data, page)

    res_dict = {}
    for i in range(len(seo)):
        res_dict.update({ind[i]: data[i]})

    context = {"data": res_dict[page], "pages": list(zip(ind, dates)), "graph": graph}
    return render(request, "statistics_and_analytics/analytics.html", context)


@login_required()
@cache_page(60 * 60)
def seo_detail_view(request, page):
    ya = YandexSEOReport.objects.all()[:10]
    go = GoogleSEOReport.objects.all()[:10]
    dr = DirectSEOReport.objects.all()[:10]
    rf = ReferralsSEOReport.objects.all()[:10]

    ind = [i for i in range(1, len(ya) + 1)]
    dates = list(map(lambda d: d.strftime("%Y-%m-%d"), [s.created for s in ya]))

    data = list(zip(ya, go, dr, rf))

    res_dict = {}

    for i in range(len(ya)):
        res_dict.update({ind[i]: data[i]})

    context = {"data": res_dict[page], "pages": list(zip(ind, dates))}
    return render(request, "statistics_and_analytics/seo-detail.html", context)


@login_required
@cache_page(60 * 60)
def ads_detail(request, page):
    ya_d = YandexDirect.objects.all()[:10]
    go_a = GoogleAds.objects.all()[:10]
    vk_a = VKAds.objects.all()[:10]
    fb_a = FacebookAds.objects.all()[:10]
    in_a = InstagramAds.objects.all()[:10]
    my_t = MyTarget.objects.all()[:10]
    ind = [i for i in range(1, len(ya_d) + 1)]
    dates = list(map(lambda d: d.strftime("%Y-%m-%d"), [s.created for s in ya_d]))

    data = list(
        zip(
            ya_d,
            go_a,
            vk_a,
            fb_a,
            in_a,
            my_t,
        )
    )

    res_dict = {}
    for i in range(len(ya_d)):
        res_dict.update({ind[i]: data[i]})

    context = {"data": res_dict[page], "pages": list(zip(ind, dates))}
    return render(request, "statistics_and_analytics/ads-report.html", context)


@login_required
@cache_page(60 * 60)
def other_detail(request, page):
    tg_a = TelegramAds.objects.all()[:10]
    em_t = EmailTracking.objects.all()[:10]
    ca_t = CallTracking.objects.all()[:10]
    ind = [i for i in range(1, len(tg_a) + 1)]
    dates = list(map(lambda d: d.strftime("%Y-%m-%d"), [s.created for s in tg_a]))

    data = list(
        zip(
            tg_a,
            em_t,
            ca_t,
        )
    )

    res_dict = {}
    for i in range(len(tg_a)):
        res_dict.update({ind[i]: data[i]})

    context = {"data": res_dict[page], "pages": list(zip(ind, dates))}
    return render(request, "statistics_and_analytics/other-ads-report.html", context)


@login_required
@cache_page(60 * 60)
def dataloading_dates(request):
    seo = SEOReport.objects.all()
    ya_d = YandexDirect.objects.all()
    go_a = GoogleAds.objects.all()
    vk_a = VKAds.objects.all()
    fb_a = FacebookAds.objects.all()
    in_a = InstagramAds.objects.all()
    my_t = MyTarget.objects.all()
    tg_a = TelegramAds.objects.all()
    em_t = EmailTracking.objects.all()
    ca_t = CallTracking.objects.all()

    data = list(
        zip(
            seo,
            ya_d,
            go_a,
            vk_a,
            fb_a,
            in_a,
            my_t,
            tg_a,
            em_t,
            ca_t,
        )
    )

    dates = [d.created for d in tg_a]
    res_dict = {}

    for i in range(len(dates)):
        current_data = data[i]
        current_data_res = [(x.income - x.all_expense) for x in current_data]
        res_dict.update({str(dates[i]): sum(current_data_res)})

    context = {"data": res_dict.items()}
    return render(request, "statistics_and_analytics/all-dates.html", context)


@login_required()
@cache_page(60 * 60)
def analytics_for_date(request, date):
    res_date = date.split(".")[0]
    seo = SEOReport.objects.filter(created__contains=res_date).first()
    ya_d = YandexDirect.objects.filter(created__contains=res_date).first()
    go_a = GoogleAds.objects.filter(created__contains=res_date).first()
    vk_a = VKAds.objects.filter(created__contains=res_date).first()
    fb_a = FacebookAds.objects.filter(created__contains=res_date).first()
    in_a = InstagramAds.objects.filter(created__contains=res_date).first()
    my_t = MyTarget.objects.filter(created__contains=res_date).first()
    tg_a = TelegramAds.objects.filter(created__contains=res_date).first()
    em_t = EmailTracking.objects.filter(created__contains=res_date).first()
    ca_t = CallTracking.objects.filter(created__contains=res_date).first()

    data = [
        seo,
        ya_d,
        go_a,
        vk_a,
        fb_a,
        in_a,
        my_t,
        tg_a,
        em_t,
        ca_t,
    ]

    context = {"data": data}
    return render(request, "statistics_and_analytics/analytics.html", context)

multi_stat/statistics_and_analytics/templates/statistics_and_analytics/ads-report.html
{% extends 'main/base.html' %}
{% load static %}
{% load mathfilters %}

{% block title %}
Рекламные кабинеты
{% endblock %}
{% block style %}
<style>
    h2 {
        text-align: center;
    }
    #main {
        min-height: 400px;
    }
    table {
        width: 100%;
        margin-bottom: 20px;
        border: 5px solid BlueViolet;
        border-top: 5px solid BlueViolet;
        border-bottom: 3px solid BlueViolet;
        border-collapse: collapse;
        outline: 3px solid BlueViolet;
        font-size: 15px;
        background: #fff!important;
        }
    table th {
        font-weight: bold;
        padding: 7px;
        background: BlueViolet;
        color: white;
        border: 1px solid #dddddd;
        text-align: left;
        font-size: 15px;
        border-top: 3px solid #fff;
        border-bottom: 3px solid BlueViolet;
    }
    table td {
        padding: 7px;
        border: 1px solid #dddddd;
        border-top: 3px solid #fff;
        border-bottom: 3px solid #fff;
        font-size: 15px;
    }
    tr:hover {
        background-color:Violet;
    }
    #span {
        margin: 6px;
        padding: 10px;
        background-color: BlueViolet;
        color: white;
        font-weight: bold;
        border-radius: 5px;
        width: 200px;
        height: 100px;
    }
    #span:hover {
        background-color: DarkOrange;
        cursor: pointer;
    }
    .reports {
        margin: 6px;
        padding: 10px;
        background-color: Grey;
        color: white;
        font-weight: bold;
        border-radius: 5px;
        width: 200px;
        height: 100px;
    }
    .reports:hover {
        background-color: DarkOrange;
        cursor: pointer;
        color: white;
        font-size: 105%;
    }

</style>
{% endblock %}

{% block content %}

<p style="text-align:center; padding-top: 15px;">
    <a href="{% url 'saa:analytics' 1 %}" class="reports">Дашборд</a>
    <a href="{% url 'saa:seo_report' 1 %}" class="reports">SEO каналы</a>
    <a href="{% url 'saa:other_ads_report' 1 %}" class="reports">Другие каналы</a>
    <a href="{% url 'saa:dates' %}" class="reports">Календарь выгрузок</a>
</p>

<div id="main" style="margin: 100px;">
    <h2>Рекламные кабинеты</h2>
    <br>
    <div style="text-align: center">
        {% for page in pages %}
        <a href="{% url 'saa:ads_report' page.0 %}" id="span">{{page.1}}</a>
        {% endfor %}
    </div>
    <br>
    <div>
        <div class="col-md-6">
            <table class="table">
                <thead>
                <tr>
                    <th>Канал</th>
                    <th>Средний чек</th>
                    <th>Визиты</th>
                    <th>Показы</th>
                    <th>CTR</th>
                    <th>CTA</th>
                    <th>Заявки</th>
                    <th>Расход</th>
                    <th>Доход</th>
                    <th>Итог</th>
                    <th>Дата</th>
                </tr>
                </thead>
                <tbody>
                {% for d in data %}
                <tr>
                    <td style="color: black; font-weight: bold">{{ d.title }}</td>
                    <td>{{ d.average_check }}</td>
                    <td>{{ d.visits }}</td>
                    <td>{{ d.views }}</td>
                    <td>{{ d.ctr }}</td>
                    <td>{{ d.cta }}</td>
                    <td>{{ d.transactions }}</td>
                    <td>{{ d.all_expense }}</td>
                    <td>{{ d.income}}</td>
                    <td id="result">{{ d.income|sub:d.all_expense }}</td>
                    <td>{{ d.created}}</td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

<script>
    const results = document.querySelectorAll("#result")
    let allSum = Number(0)
    results.forEach(res => {
       if(Number(res.textContent) > Number(0)){
        allSum += Number(res.textContent);
       }
    })

    const medianNumber = Number(allSum / results.length);


    results.forEach(res => {
        if(Number(res.textContent) <= 0){
            res.parentNode.style.backgroundColor="Crimson";
        }
        if(Number(res.textContent) > (Number(medianNumber) * 1.3)){
            res.parentNode.style.backgroundColor="ForestGreen";
        }
    })
</script>

{% endblock %}

multi_stat/statistics_and_analytics/templates/statistics_and_analytics/all-dates.html
{% extends 'main/base.html' %}
{% load static %}
{% load mathfilters %}

{% block title %}
Календарь выгрузок
{% endblock %}
{% block style %}
<style>
    h2 {
        text-align: center;
    }
    #main {
        min-height: 400px;
    }
    table {
        width: 100%;
        margin-bottom: 20px;
        border: 5px solid BlueViolet;
        border-top: 5px solid BlueViolet;
        border-bottom: 3px solid BlueViolet;
        border-collapse: collapse;
        outline: 3px solid BlueViolet;
        font-size: 15px;
        background: #fff!important;
        }
    table th {
        font-weight: bold;
        padding: 7px;
        background: BlueViolet;
        color: white;
        border: 1px solid #dddddd;
        text-align: left;
        font-size: 15px;
        border-top: 3px solid #fff;
        border-bottom: 3px solid BlueViolet;
    }
    table td {
        padding: 7px;
        border: 1px solid #dddddd;
        border-top: 3px solid #fff;
        border-bottom: 3px solid #fff;
        font-size: 15px;
    }
    tr:hover {
        background-color:Violet;
    }
    #span {
        margin: 6px;
        padding: 10px;
        background-color: BlueViolet;
        color: white;
        font-weight: bold;
        border-radius: 5px;
        width: 200px;
        height: 100px;
    }
    #span:hover {
        background-color: DarkOrange;
        cursor: pointer;
    }
    .reports {
        margin: 6px;
        padding: 10px;
        background-color: Grey;
        color: white;
        font-weight: bold;
        border-radius: 5px;
        width: 200px;
        height: 100px;
    }
    .reports:hover {
        background-color: DarkOrange;
        cursor: pointer;
        color: white;
        font-size: 105%;
    }

</style>
{% endblock %}

{% block content %}


<p style="text-align:center; padding-top: 15px;">
    <a href="{% url 'saa:analytics' 1 %}" class="reports">Дашборд</a>
    <a href="{% url 'saa:seo_report' 1 %}" class="reports">SEO каналы</a>
    <a href="{% url 'saa:ads_report' 1 %}" class="reports">Рекламные кабинеты</a>
    <a href="{% url 'saa:other_ads_report' 1 %}" class="reports">Другие каналы</a>
</p>

<div id="main" style="margin: 100px;">
    <h2>Календарь выгрузок</h2>
    <br>
    <div>
        <div class="col-md-6">
            <table class="table">
                <thead>
                <tr>
                    <th>Дата выгрузки</th>
                    <th>Прибыль</th>
                </tr>
                </thead>
                <tbody>
                {% for d in data %}
                <tr>
                    <td><a href="{% url 'saa:a_for_dates' date=d.0 %}">{{ d.0|truncatechars:11 }}</a></td>
                    <td>{{ d.1 }}</td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>


{% endblock %}

multi_stat/statistics_and_analytics/templates/statistics_and_analytics/analytics.html
{% extends 'main/base.html' %}
{% load static %}
{% load mathfilters %}

{% block title %}
Аналитика {{profile.username}}
{% endblock %}
{% block style %}
<style>
    h2 {
        text-align: center;
    }
    #main {
        min-height: 400px;
    }
    table {
        width: 100%;
        margin-bottom: 20px;
        border: 5px solid BlueViolet;
        border-top: 5px solid BlueViolet;
        border-bottom: 3px solid BlueViolet;
        border-collapse: collapse;
        outline: 3px solid BlueViolet;
        font-size: 15px;
        background: #fff!important;
        }
    table th {
        font-weight: bold;
        padding: 7px;
        background: BlueViolet;
        color: white;
        border: 1px solid #dddddd;
        text-align: left;
        font-size: 15px;
        border-top: 3px solid #fff;
        border-bottom: 3px solid BlueViolet;
    }
    table td {
        padding: 7px;
        border: 1px solid #dddddd;
        border-top: 3px solid #fff;
        border-bottom: 3px solid #fff;
        font-size: 15px;
    }
    tr:hover {
        background-color:Violet;
    }
    #span {
        margin: 6px;
        padding: 10px;
        background-color: BlueViolet;
        color: white;
        font-weight: bold;
        border-radius: 5px;
        width: 200px;
        height: 100px;
    }
    #span:hover {
        background-color: DarkOrange;
        cursor: pointer;
    }
    .reports {
        margin: 6px;
        padding: 10px;
        background-color: Grey;
        color: white;
        font-weight: bold;
        border-radius: 5px;
        width: 200px;
        height: 100px;
    }
    .reports:hover {
        background-color: DarkOrange;
        cursor: pointer;
        color: white;
        font-size: 105%;
    }

</style>
{% endblock %}

{% block content %}

<p style="text-align:center; padding-top: 15px;">
    <a href="{% url 'saa:seo_report' 1 %}" class="reports">SEO каналы</a>
    <a href="{% url 'saa:ads_report' 1 %}" class="reports">Рекламные кабинеты</a>
    <a href="{% url 'saa:other_ads_report' 1 %}" class="reports">Другие каналы</a>
    <a href="{% url 'saa:dates' %}" class="reports">Календарь выгрузок</a>
</p>

<div id="main" style="margin: 100px; margin-top: 50px;">
    <h2>Мультиканальная аналитика</h2>
    <br>
    {% if pages %}
    <div style="text-align: center">
        {% for page in pages %}
        <a href="{% url 'saa:analytics' page.0 %}" id="span">{{page.1}}</a>
        {% endfor %}
    </div>
    <br>
    {% endif %}
    <div>
        <div class="col-md-6">
            <table class="table">
                <thead>
                <tr>
                    <th>Канал</th>
                    <th>Визиты</th>
                    <th>Заявки</th>
                    <th>Расход</th>
                    <th>Доход</th>
                    <th>Итог</th>
                    <th>Дата</th>
                </tr>
                </thead>
                <tbody>
                {% for d in data %}
                <tr>
                    <td style="color: black; font-weight: bold">{{ d.title }}</td>
                    <td>{{ d.visits }}</td>
                    <td>{{ d.transactions }}</td>
                    <td>{{ d.all_expense }}</td>
                    <td>{{ d.income }}</td>
                    <td id="result">{{ d.income|sub:d.all_expense }}</td>
                    <td>{{ d.created }}</td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    {% if graph %}
    <div style="text-align: center">
        <img src="{% static graph %}">
    </div>
    {% endif %}
</div>

<script>
    const results = document.querySelectorAll("#result")
    let allSum = Number(0)
    results.forEach(res => {
       if(Number(res.textContent) > Number(0)){
        allSum += Number(res.textContent);
       }
    })

    const medianNumber = Number(allSum / results.length);


    results.forEach(res => {
        if(Number(res.textContent) <= 0){
            res.parentNode.style.backgroundColor="Crimson";
        }
        if(Number(res.textContent) > (Number(medianNumber) * 1.5)){
            res.parentNode.style.backgroundColor="ForestGreen";
        }
    })
</script>

{% endblock %}