multi_stat/main/urls.py
from django.urls import path
from .views import index, contacts, about

app_name = "main"

urlpatterns = [
    path("contacts/", contacts, name="contacts"),
    path("about-us/", about, name="about"),
    path("", index, name="index"),
]

multi_stat/multi_stat/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("analytic/", include("statistics_and_analytics.urls")),
    path("socials/", include("socials.urls")),
    path("", include("main.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

multi_stat/socials/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from .views import register, ProfileUpdateView, ProfileView
from django.conf import settings
from django.conf.urls.static import static

app_name = "socials"

urlpatterns = (
    [
        path(
            "login/",
            LoginView.as_view(template_name="socials/login.html"),
            name="login",
        ),
        path("logout/", LogoutView.as_view(next_page="main:index"), name="logout"),
        path("register/", register, name="register"),
        path(
            "profile/<int:pk>/update/",
            ProfileUpdateView.as_view(),
            name="profile_update",
        ),
        path("profile/<int:pk>/", ProfileView.as_view(), name="profile_view"),
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

multi_stat/statistics_and_analytics/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import (
    analytics,
    seo_detail_view,
    ads_detail,
    other_detail,
    dataloading_dates,
    analytics_for_date,
)

app_name = "saa"

urlpatterns = (
    [
        path("seo-report/<int:page>/", seo_detail_view, name="seo_report"),
        path("other-ads-report/<int:page>/", other_detail, name="other_ads_report"),
        path("ads-report/<int:page>/", ads_detail, name="ads_report"),
        path("dashboard/<int:page>/", analytics, name="analytics"),
        path("dataloading-dates/", dataloading_dates, name="dates"),
        path("analytic-for-date/<str:date>/", analytics_for_date, name="a_for_dates"),
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

multi_stat/main/views.py
from django.shortcuts import render


def index(request):
    return render(request, "main/pages/index.html")


def contacts(request):
    return render(request, "main/pages/contacts.html")


def about(request):
    return render(request, "main/pages/about.html")

multi_stat/main/templates/main/base.html
{% load static %}

<!DOCTYPE html>
<html style="font-size: 16px;" lang="ru">
<head>
    <link rel="icon" type="image/png" href="{% static 'img/cupy_icon.png' %}"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">
    <meta name="keywords"
          content="Mobile App Development, ​Stimulate your cognitive abilities while having fun, What We Do, Testimonials, Company Services, ​Love the way you work together?, Our Portfolio, About Us, ​Our way, Get in Touch, ​Level up your brand">
    <meta name="description" content="">
    <title>{% block title %}MultiStat сервис мультиканальной аналитики{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/nicepage.css' %}" media="screen">
    <link rel="stylesheet" href="{% static 'css/Главная.css' %}" media="screen">
    {% if 'socials' in request.path %}
    <link rel="stylesheet" href="{% static 'css/Страница-1.css' %}" media="screen">
    {% endif %}
    <script class="u-script" type="text/javascript" src="{% static 'js/jquery.js' %}" defer=""></script>
    <script class="u-script" type="text/javascript" src="{% static 'js/nicepage.js' %}" defer=""></script>
    <meta name="generator" content="Nicepage 6.0.3, nicepage.com">
    <meta name="referrer" content="origin">
    <link id="u-theme-google-font" rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i|Open+Sans:300,300i,400,400i,500,500i,600,600i,700,700i,800,800i">
    <link id="u-page-google-font" rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i|Montserrat:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i">


    <script type="application/ld+json">{
        "@context": "http://schema.org",
        "@type": "Organization",
        "name": "",
        "logo": "images/cupy_icon.png"
    }</script>
    <meta name="theme-color" content="#a37fdf">
    <meta property="og:title" content="Главная">
    <meta property="og:type" content="website">
    <meta data-intl-tel-input-cdn-path="intlTelInput/">
    {% block style %}
    {% endblock %}
</head>
<body data-home-page="Главная.html" data-home-page-title="Главная" data-path-to-root="./" data-include-products="false"
      class="u-body u-xl-mode" data-lang="ru">
<header class="u-clearfix u-grey-80 u-header u-sticky u-sticky-19c7 u-header" id="sec-d402">
    <div class="u-clearfix u-sheet u-sheet-1">
        <a href="{% url 'main:index' %}" class="u-image u-logo u-image-1" data-image-width="1024"
           data-image-height="1024">
            <img src="{% static 'img/cupy_icon.png' %}" class="u-logo-image u-logo-image-1">
        </a>
        <nav class="u-menu u-menu-hamburger u-offcanvas u-menu-1">
            <div class="menu-collapse" style="font-size: 1rem; letter-spacing: 0px;">
                <a class="u-button-style u-custom-left-right-menu-spacing u-custom-padding-bottom u-custom-text-active-color u-custom-text-color u-custom-text-hover-color u-custom-top-bottom-menu-spacing u-nav-link u-text-active-palette-1-base u-text-hover-palette-2-base"
                   href="#">
                    <svg class="u-svg-link" viewBox="0 0 24 24">
                        <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#menu-hamburger"></use>
                    </svg>
                    <svg class="u-svg-content" version="1.1" id="menu-hamburger" viewBox="0 0 16 16" x="0px" y="0px"
                         xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg">
                        <g>
                            <rect y="1" width="16" height="2"></rect>
                            <rect y="7" width="16" height="2"></rect>
                            <rect y="13" width="16" height="2"></rect>
                        </g>
                    </svg>
                </a>
            </div>
            <div class="u-custom-menu u-nav-container">
                <ul class="u-nav u-spacing-30 u-unstyled u-nav-1">
                    <li class="u-nav-item"><a
                            class="u-border-2 u-border-active-palette-1-base u-border-hover-palette-1-light-1 u-border-no-left u-border-no-right u-border-no-top u-button-style u-nav-link u-text-active-palette-1-base u-text-hover-palette-5-light-1 u-text-white"
                            href="{% url 'main:index' %}" style="padding: 10px 0px;">Главная</a>
                    </li>
                    {% if request.user.is_authenticated and request.user.username != 'admin' and request.user.profile.id != '' %}
                    <li class="u-nav-item"><a
                            class="u-border-2 u-border-active-palette-1-base u-border-hover-palette-1-light-1 u-border-no-left u-border-no-right u-border-no-top u-button-style u-nav-link u-text-active-palette-1-base u-text-hover-palette-5-light-1 u-text-white"
                            href="{% url 'saa:analytics' 1 %}" style="padding: 10px 0px;">Дашборд</a>
                    </li>
                    <li class="u-nav-item"><a
                            class="u-border-2 u-border-active-palette-1-base u-border-hover-palette-1-light-1 u-border-no-left u-border-no-right u-border-no-top u-button-style u-nav-link u-text-active-palette-1-base u-text-hover-palette-5-light-1 u-text-white"
                            href="{% url 'socials:profile_view' pk=request.user.profile.id%}" style="padding: 10px 0px;">Профиль</a>
                    </li>
                    <li class="u-nav-item">
                        <form method="post" action="{% url 'socials:logout' %}">
                            {% csrf_token %}
                            <button style="padding: 10px 0px; cursor:pointer"
                                    class="u-border-2 u-border-active-palette-1-base u-border-hover-palette-1-light-1 u-border-no-left u-border-no-right u-border-no-top u-button-style u-nav-link u-text-active-palette-1-base u-text-hover-palette-5-light-1 u-text-white"
                                    type="submit">Выход
                            </button>
                        </form>
                    </li>
                    {% else %}
                    <li class="u-nav-item"><a
                            class="u-border-2 u-border-active-palette-1-base u-border-hover-palette-1-light-1 u-border-no-left u-border-no-right u-border-no-top u-button-style u-nav-link u-text-active-palette-1-base u-text-hover-palette-5-light-1 u-text-white"
                            href="{% url 'socials:login' %}" style="padding: 10px 0px;">Вход</a>
                    </li>
                    <li class="u-nav-item"><a
                            class="u-border-2 u-border-active-palette-1-base u-border-hover-palette-1-light-1 u-border-no-left u-border-no-right u-border-no-top u-button-style u-nav-link u-text-active-palette-1-base u-text-hover-palette-5-light-1 u-text-white"
                            href="{% url 'socials:register' %}" style="padding: 10px 0px;">Регистрация</a>
                    </li>
                    {% endif %}
                    <li class="u-nav-item"><a
                            class="u-border-2 u-border-active-palette-1-base u-border-hover-palette-1-light-1 u-border-no-left u-border-no-right u-border-no-top u-button-style u-nav-link u-text-active-palette-1-base u-text-hover-palette-5-light-1 u-text-white"
                            href="{% url 'main:contacts' %}" style="padding: 10px 0px;">Контакты</a>
                    </li>
                    <li class="u-nav-item"><a
                            class="u-border-2 u-border-active-palette-1-base u-border-hover-palette-1-light-1 u-border-no-left u-border-no-right u-border-no-top u-button-style u-nav-link u-text-active-palette-1-base u-text-hover-palette-5-light-1 u-text-white"
                            href="{% url 'main:about' %}" style="padding: 10px 0px;">О нас</a>
                    </li>
                </ul>
            </div>
            <div class="u-custom-menu u-nav-container-collapse">
                <div class="u-black u-container-style u-inner-container-layout u-opacity u-opacity-95 u-sidenav">
                    <div class="u-inner-container-layout u-sidenav-overflow">
                        <div class="u-menu-close"></div>
                        <ul class="u-align-center u-nav u-popupmenu-items u-unstyled u-nav-2">
                            <li class="u-nav-item"><a class="u-button-style u-nav-link" href="{% url 'main:index' %}">Главная</a>
                            </li>
                            {% if request.user.is_authenticated and request.user.username != 'admin' and request.user.profile.id != '' %}
                            <li class="u-nav-item"><a class="u-button-style u-nav-link" href="{% url 'saa:analytics' 1 %}">Дашборд</a>
                            </li>
                            <li class="u-nav-item"><a class="u-button-style u-nav-link" href="{% url 'socials:profile_view' pk=request.user.profile.id %}">Профиль</a>
                            </li>
                            <li class="u-nav-item">
                                <form method="post" action="{% url 'socials:logout' %}">
                                    {% csrf_token %}
                                    <button style="padding: 10px 0px; cursor:pointer"
                                            class="u-button-style u-nav-link"
                                            type="submit">Выход
                                    </button>
                                </form>
                            </li>
                            {% else %}
                            <li class="u-nav-item"><a class="u-button-style u-nav-link"
                                                      href="{% url 'socials:login' %}">Вход</a>
                            </li>
                            <li class="u-nav-item"><a class="u-button-style u-nav-link" href="{% url 'socials:register' %}">Регистрация</a>
                            </li>
                            {% endif %}
                            <li class="u-nav-item"><a class="u-button-style u-nav-link" href="{% url 'main:contacts' %}">Контакты</a>
                            </li>
                            <li class="u-nav-item"><a class="u-button-style u-nav-link" href="{% url 'main:about' %}">О нас</a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="u-black u-menu-overlay u-opacity u-opacity-70"></div>
            </div>
        </nav>
    </div>
</header>

{% block content %}
{% endblock %}


<footer class="u-align-center u-clearfix u-footer u-grey-80 u-footer" id="sec-6d3f">
    <div class="u-clearfix u-sheet u-sheet-1">
        <p class="u-small-text u-text u-text-variant u-text-1"><q>Если вашего бизнеса нет в интернете, то вас нет в
            бизнесе</q> — Стив Джобс</p>
    </div>
</footer>

</body>
</html>